Various compilation and unit test fixes.

diff --git a/test/check-build b/test/check-build
--- a/test/check-build
+++ b/test/check-build
@@ -3,12 +3,12 @@
 failure=0
 
 config_h_in=$(dirname "$0")/../config.h.in
-win32_config_h=$(dirname "$0")/../win32/config.h
+msvc_config_h=$(dirname "$0")/../msvc/config.h
 
 for key in $(sed -ne 's/.*#undef *\([A-Za-z0-9_]*\).*/\1/p' "$config_h_in");
 do
-  if ! grep '[ef] \<'"$key"'\>' "$win32_config_h" >/dev/null 2>&1; then
-    echo "error: $key missing from win32/config.h"
+  if ! grep '[ef] \<'"$key"'\>' "$msvc_config_h" >/dev/null 2>&1; then
+    echo "error: $key missing from msvc/config.h"
     failure=1
   fi
 done
